/**
 * Build script.
 *
 * Four independent single-entry Vite builds. Each entry is emitted as one
 * self-contained file: the service worker and the content script must not
 * import each other or a shared chunk, because a service worker cannot use ES
 * module imports unless it is declared as `"type": "module"` and a classic
 * content script cannot import anything at all.
 *
 *   dist/background.js         service worker (IIFE)
 *   dist/cosmetic.js           content script (IIFE)
 *   dist/popup/popup.html      popup page
 *   dist/options/options.html  options page
 *   dist/manifest.json         copied from public/
 *   dist/icons/*.png           generated by scripts/gen-icons.mjs
 */

import { build } from 'vite';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'dist');

async function buildScript(entry, fileName) {
  await build({
    root,
    configFile: false,
    logLevel: 'warn',
    build: {
      outDir: dist,
      emptyOutDir: false,
      target: 'chrome120',
      minify: false,
      sourcemap: false,
      lib: {
        entry: path.join(root, entry),
        formats: ['iife'],
        // Required by Vite for IIFE output; the bundle has no exports, so the
        // name is never actually used.
        name: 'QuietBlockBundle',
        fileName: () => fileName,
      },
    },
  });
}

async function buildPage(name) {
  await build({
    root: path.join(root, 'src', name),
    base: './',
    configFile: false,
    logLevel: 'warn',
    build: {
      outDir: path.join(dist, name),
      emptyOutDir: false,
      target: 'chrome120',
      minify: false,
      sourcemap: false,
      rollupOptions: {
        input: path.join(root, 'src', name, `${name}.html`),
        output: {
          entryFileNames: `${name}.js`,
          assetFileNames: `${name}[extname]`,
        },
      },
    },
  });
}

async function main() {
  const started = Date.now();
  await fs.rm(dist, { recursive: true, force: true });

  await buildScript('src/background/index.ts', 'background.js');
  await buildScript('src/content/cosmetic.ts', 'cosmetic.js');
  await buildPage('popup');
  await buildPage('options');

  await fs.cp(path.join(root, 'public'), dist, { recursive: true });

  const icons = path.join(dist, 'icons');
  await fs.mkdir(icons, { recursive: true });
  const { generateIcons } = await import('./gen-icons.mjs');
  await generateIcons(icons);

  const files = await fs.readdir(dist, { withFileTypes: true });
  const summary = [];
  for (const entry of files) {
    if (entry.isDirectory()) {
      const nested = await fs.readdir(path.join(dist, entry.name));
      summary.push(`${entry.name}/ (${nested.length} files)`);
    } else {
      summary.push(entry.name);
    }
  }
  console.log(`Built dist/ in ${Date.now() - started} ms: ${summary.join(', ')}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
